[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "utils"
version = "0.1.0"
description = "BioFeatureFactory utilities"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["utils*"]
